from __future__ import annotations
import io
from datetime import datetime
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (SimpleDocTemplate, Paragraph, Spacer, Table,
                                 TableStyle, HRFlowable)

CLINIC_NAME  = "Little Angels Superspecialty Eye Clinic"
CLINIC_SUB   = "Dr. Trupti Kadam Lambat — Pediatric, Neuro, Squint & Comprehensive Ophthalmologist"
CLINIC_CITY  = "Nagpur, Maharashtra"

_styles = getSampleStyleSheet()
_title_style = ParagraphStyle("ClinicTitle", parent=_styles["Title"], fontSize=18, spaceAfter=2)
_sub_style   = ParagraphStyle("ClinicSub", parent=_styles["Normal"], fontSize=10, textColor=colors.grey)
_h2_style    = ParagraphStyle("SectionHead", parent=_styles["Heading2"], fontSize=13,
                               spaceBefore=14, spaceAfter=6, textColor=colors.HexColor("#1e3a5f"))
_normal      = _styles["Normal"]


def _header(elements, doc_title: str):
    elements.append(Paragraph(CLINIC_NAME, _title_style))
    elements.append(Paragraph(CLINIC_SUB, _sub_style))
    elements.append(Paragraph(CLINIC_CITY, _sub_style))
    elements.append(Spacer(1, 6))
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#1e3a5f"), thickness=1))
    elements.append(Spacer(1, 10))
    elements.append(Paragraph(doc_title, _h2_style))


def _kv_table(rows: list[tuple[str, str]]) -> Table:
    data = [[Paragraph(f"<b>{k}</b>", _normal), Paragraph(str(v) if v not in (None, "") else "—", _normal)]
            for k, v in rows]
    t = Table(data, colWidths=[55*mm, 105*mm])
    t.setStyle(TableStyle([
        ("BOX", (0, 0), (-1, -1), 0.5, colors.HexColor("#cccccc")),
        ("INNERGRID", (0, 0), (-1, -1), 0.5, colors.HexColor("#e0e0e0")),
        ("BACKGROUND", (0, 0), (0, -1), colors.HexColor("#f2f6fa")),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    return t


def _footer(elements):
    elements.append(Spacer(1, 16))
    elements.append(HRFlowable(width="100%", color=colors.HexColor("#cccccc"), thickness=0.5))
    elements.append(Spacer(1, 4))
    elements.append(Paragraph(
        f"Generated by NeuroVista AI on {datetime.now().strftime('%d %b %Y, %I:%M %p')}",
        _sub_style))


def generate_registration_pdf(patient: dict, consent: dict | None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    elements = []
    _header(elements, f"Patient Registration — #{patient['id']}")

    elements.append(_kv_table([
        ("Child's Name", patient.get("child_name")),
        ("Gender", patient.get("child_sex")),
        ("Age", f"{patient.get('child_age_years', '—')} years"),
        ("Date of Birth", patient.get("child_dob")),
        ("Guardian", patient.get("guardian_name")),
        ("Relation", patient.get("guardian_relation")),
        ("Phone", patient.get("phone")),
        ("Address", patient.get("address")),
        ("Registered On", patient.get("created_at")),
    ]))

    if consent:
        elements.append(Paragraph("Consent Status", _h2_style))
        yn = lambda v: "✅ Yes" if v else "❌ No"
        elements.append(_kv_table([
            ("Data Consent", yn(consent.get("data_consent"))),
            ("Photo Consent", yn(consent.get("photo_consent"))),
            ("Research Consent", yn(consent.get("research_consent"))),
        ]))

    _footer(elements)
    doc.build(elements)
    return buf.getvalue()


def generate_appointment_pdf(patient: dict, appointment: dict | None) -> bytes:
    buf = io.BytesIO()
    doc = SimpleDocTemplate(buf, pagesize=A4, topMargin=20*mm, bottomMargin=20*mm)
    elements = []
    _header(elements, f"Appointment Confirmation — #{patient['id']}")

    elements.append(_kv_table([
        ("Child's Name", patient.get("child_name")),
        ("Age", f"{patient.get('child_age_years', '—')} years"),
        ("Guardian", patient.get("guardian_name")),
        ("Phone", patient.get("phone")),
    ]))

    elements.append(Paragraph("Appointment Details", _h2_style))
    if appointment:
        visit_type = "Walk-in (today)" if appointment.get("visit_type") == "walkin" else "Scheduled"
        elements.append(_kv_table([
            ("Visit Type", visit_type),
            ("Preferred Date/Time", appointment.get("preferred_datetime") or "N/A — walk-in"),
            ("Special Needs", appointment.get("special_needs")),
            ("Confirmed On", appointment.get("confirmed_at")),
        ]))
    else:
        elements.append(Paragraph("No appointment recorded yet.", _normal))

    elements.append(Spacer(1, 10))
    elements.append(Paragraph(
        "Please arrive 10 minutes early and bring any previous medical records. "
        "Clinic hours: Mon–Sat, 10am–6pm.", _normal))

    _footer(elements)
    doc.build(elements)
    return buf.getvalue()
